### ISSUE TITLE
AttributeError: type object 'WNPRedux' has no attribute 'start'

### ISSUE THREAD

**Issue by Slavko56789** [keifufu/WebNowPlaying-Redux-OBS#3]
![image](https://user-images.githubusercontent.com/128586511/236185723-dd58418f-51c7-441d-9eb0-aa35813255ab.png)

**Comment by keifufu** [comment]
Don't download the python file from the repository. It's not been put in "Releases" for a reason. Please download the file from the releases tab.

**Comment by Slavko56789** [comment]
All worked 3 days ago OBS updated, but does not display the track in the obs
![image](https://user-images.githubusercontent.com/128586511/236288744-50c99e34-36f6-4c89-8330-865ac0db7aa7.png)
![image](https://user-images.githubusercontent.com/128586511/236288774-1ad50034-7e6d-47df-b2f7-b59f10191226.png)

**Comment by keifufu** [comment]
Ah, I see the issue. It loads the widgets html straight from this github repo.
In this case I updated the widgets without updating the script, making them incompatible.
I rolled back the affected files for now. It should start working again either immediately or in a few hours after some cache expired. You can also try selecting the widgets browser source and clicking "Refresh".

Next time this happens, it's probably because there is a new release available.

**Comment by Slavko56789** [comment]
All works thank you very much)
